---
title: "R Notebook"
output: html_notebook
---

###Front Matter
```{r, message= FALSE}
library(DataComputing)
library(tidyverse)
library(mosaic)
library(ggplot2)
library(maps)
```


### Upload Data Sets
```{r, message= FALSE}
###Using file.choose we store the csv address in dataset
Orig_Fifa_data<-read_csv("/Users/davidweiss/Desktop/Fall 2019/Stat 184/Final Project/FIFA DATA.csv")


```

```{r}
head(Orig_Fifa_data)
str(Orig_Fifa_data)
```


### Clean the Data
```{r}
Cleaned_fifa_data<-
  Orig_Fifa_data %>%
  select("Name", "Age", "Nationality", "Overall", "Potential", "Club", "Value", "Wage", "Preferred Foot", "Weak Foot", "Skill Moves", "Work Rate", "Position", "Height", "Weight", "Crossing",	"Finishing",	"HeadingAccuracy",	"ShortPassing",	"Volleys",	"Dribbling", "Curve",	"FKAccuracy",	"LongPassing",	"BallControl",	"Acceleration",	"SprintSpeed",	"Agility",	"Reactions",	"Balance",	"ShotPower",	"Jumping",	"Stamina",	"Strength",	"LongShots",	"Aggression",	"Interceptions",	"Positioning",	"Vision",	"Penalties",	"Composure",	"Marking",	"StandingTackle",	'SlidingTackle',	"GKDiving",	"GKHandling",	"GKKicking",	"GKPositioning",	"GKReflexes") %>%
  mutate(Weight=parse_number(Weight),
         Value=parse_number(Value),
         Wage=parse_number(Wage),
         Height=sapply(strsplit(sub("(\\d+)'(\\d+).*", "\\1-\\2", x = Height), "-"), function(x)
       as.numeric(x[1]) * 30.48 + as.numeric(x[2]) * 2.54)) 

  
  
```

```{r}
head(Cleaned_fifa_data)
```


```{r}
Top<-
  Cleaned_fifa_data%>%
  mutate(rank=rank(desc(Overall))) %>%
  filter(rank<100) %>%
  rename("region"=Nationality)
 
Top 
```

```{r}
Grouped_top <-
  Top %>%
  group_by(region) %>%
  summarise(count=n())

Grouped_top
```


### Join
```{r}
World_map<- map_data("world")
Joined_top <-
  World_map %>%
  left_join(Grouped_top)
Joined_top
```





Create Function

```{r}
top_soccer_function <-function(x){
  
  Top<-
  Cleaned_fifa_data%>%
  mutate(rank=rank(desc(Overall))) %>%
  filter(rank<x) %>%
  rename("region"=Nationality)
  
  Grouped_top <-
  Top %>%
  group_by(region) %>%
  summarise(count=n())
  
  World_map<- map_data("world")
  Joined_top <-
  World_map %>%
  left_join(Grouped_top)
  
  Map<-
    ggplot(Joined_top, aes(x = long, y = lat, group=group)) +
    geom_polygon(aes(fill=count), colour = "white")+
    scale_fill_viridis_c(option = "C")
  
  return(Map)
}
top_soccer_function(100)
```

Test function

```{r}
top_soccer_function(600)
```



